<?php

/**
 * =============================================================================
 * LOCAL CONFIGURATION OVERRIDE INSTRUCTIONS
 * =============================================================================
 *
 * This file (`config.php`) contains the default configuration settings.
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY for your local setup, as your
 * changes will be overwritten when you update the project via Git.
 *
 * Instead, follow these steps to create local overrides:
 *
 * 1. CREATE A NEW FILE: In this same directory, create a file named:
 *    `config.local.php`
 *
 * 2. COPY BELOW CONFIGURATION + DEFINE OVERRIDES: Inside `config.local.php`
 *
 * =============================================================================
 */

define('BEANSTALK_CONSOLE_VERSION', '1.9.1');

$localConfigFile = __DIR__ . '/config.local.php';
if (file_exists($localConfigFile) && is_readable($localConfigFile) && basename(__FILE__) !== 'config.local.php') {
    require $localConfigFile;
    if (count($GLOBALS['config'], true) != 1 && count($GLOBALS['config'], true) < 22) {
        die('Please update your config.local.php with all new options. You are missing some.');
    }
    if (is_array($GLOBALS['config']['servers'])) {
        return;
    }
}
/**
 * =============================================================================
 * LOCAL CONFIGURATION `config.local.php` CONTENTS BELOW
 * =============================================================================
 */

$GLOBALS['config'] = array(
    /**
     * List of servers available for all users
     */
    'servers' => array(/* 'Local Beanstalkd' => 'beanstalk://localhost:11300', ... */),
    /**
     * Saved samples jobs are kept in this file, must be writable
     */
    'storage' => dirname(__FILE__) . DIRECTORY_SEPARATOR . 'storage.json',
    /**
     * Optional Basic Authentication
     */
    'auth' => array(
        'enabled' => false,
        'username' => 'admin',
        'password' => 'password',
    ),

    /**
     * Default UI settings (used when no cookie is present).
     * These values will be overridden by user-specific selection in Settings screen and kept in cookies.
     * Keys use a positive 'enableFeature' convention where applicable.
     * 'true' means the feature is ON by default.
     * 'false' means the feature is OFF by default.
     */
    'settings' => array(
        // Numeric settings
        'tubePauseSeconds'          => -1,    // Default: -1 (uses beanstalkd default of 1 hour)
        'autoRefreshTimeoutMs'      => 500,   // Default: 500ms interval for auto-refresh
        'searchResultLimit'         => 25,    // Default: 25 results in search

        // Boolean settings (true = enabled/checked by default)
        'enableJsonDecode'          => true,  // Default: Job data IS json_decoded by default
        'enableJobDataHighlight'    => true,  // Default: Job data highlighting IS enabled by default
        'enableAutoRefreshLoad'     => false,  // Default: Auto-refresh IS disabled on page load
        'enableUnserialization'     => false, // Default: Job data IS NOT unserialized by default
        'enableBase64Decode'        => false, // Default: Job data IS NOT base64_decoded by default
    ),

    /**
     * Per-server, per-tube job body display overrides.
     */
    'tubeBodyDisplay' => array(
        // null means dirname($config['storage']) . '/tube-body-display.json'.
        'storage' => null,
    ),

    /**
     * Review batch settings.
     */
    'review' => array(
        // Enables the review batch UI and actions. Set false to disable this feature entirely.
        'enabled' => false,
        // Number of jobs processed per AJAX chunk while preparing reviews and while running chunked return/delete operations.
        'chunkSize' => 200,
        // Number of characters shown in the review table body preview before truncation.
        'bodyPreviewLength' => 100,
        // Allow preparing ready jobs only when stats-tube reports no watchers/waiters for the source tube.
        'allowReadyWhenUnwatched' => true,
        // Allow preparing delayed jobs only when stats-tube reports no watchers/waiters for the source tube.
        'allowDelayedWhenUnwatched' => true,
        // Dangerous: allow ready job review even when workers may be watching. Requires explicit checkbox in the UI.
        'allowUnsafeReadyOverride' => false,
        // Dangerous: allow delayed job review even when workers may be watching. Requires explicit checkbox in the UI.
        'allowUnsafeDelayedOverride' => false,
        // If true, the UI never offers body snapshot capture and the backend refuses to create body snapshots.
        // Body snapshots preserve review-time payloads, but can create large local files and impact review-page/body-load performance.
        'neverIncludeBodySnapshot' => false,
        // Directory for review metadata files. null means dirname($config['storage']) . '/review-batches'.
        // This stores audit JSONL, materialized current summaries, operation metadata, and optional body snapshot JSONL files.
        'storagePath' => null,
    ),
);
